# Generated by Django 4.2.9 on 2024-01-30 08:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='BookLanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Book Language',
                'verbose_name_plural': 'Book Languages',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categories',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='GenderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PublisherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Publishers',
                'verbose_name_plural': 'Publishers',
            },
        ),
        migrations.CreateModel(
            name='TranslatorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=50)),
                ('write_type', models.CharField(max_length=50)),
                ('page_size', models.PositiveIntegerField()),
                ('cover', models.IntegerField(choices=[(1, 'Hard'), (0, 'Soft')])),
                ('paper_format', models.IntegerField(choices=[(1, 'A3'), (2, 'A4'), (3, 'A5')])),
                ('publication_date', models.DateField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.booklanguagemodel')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='books.publishermodel')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='books.translatormodel')),
            ],
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('main_image', models.ImageField(upload_to='main_image')),
                ('description', models.TextField(blank=True, null=True)),
                ('book_created', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stars', models.FloatField(default=0.0)),
                ('cash_status', models.BooleanField(default=True)),
                ('readed', models.IntegerField(default=0)),
                ('reading', models.IntegerField(default=0)),
                ('well_read', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('real_price', models.FloatField(default=0)),
                ('discount', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)])),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='books', to='books.authormodel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.categorymodel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BookImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_images')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='books.bookmodel')),
            ],
        ),
    ]
