# Generated by Django 4.2.9 on 2024-01-30 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='features',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.RESTRICT, to='books.featuresmodel'),
            preserve_default=False,
        ),
    ]
